application: formidable-pact-829
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /font
  static_dir: font
- url: /img
  static_dir: img

- url: /.*
  script: zemis.application


libraries:
- name: webapp2
  version: '2.5.2'
- name: jinja2
  version: '2.6'
